version: 3.0.0.{build}
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true 
  matrix:
  - job_name: windows
    appveyor_build_worker_image: Visual Studio 2019
  - job_name: linux
    appveyor_build_worker_image: Ubuntu
matrix:
  fast_finish: true

for:
  -
    matrix:
      only:
        - job_name: windows
    init:
      # default is: core.autocrlf input
      - git config --global core.autocrlf true
    build_script:
      - ps: cd $env:APPVEYOR_BUILD_FOLDER\src
      - ps: dotnet restore --verbosity quiet
      - ps: dotnet add .\SmartFormat.Tests\SmartFormat.Tests.csproj package AltCover
      - ps: dotnet build SmartFormat.sln /verbosity:minimal /t:rebuild /p:configuration=release /nowarn:CS1591,CS0618
      - ps: |
          $version = "2.7.0"
          $versionFile = $version + "." + ${env:APPVEYOR_BUILD_NUMBER}

          if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
              $version = $version + "-PR" + $env:APPVEYOR_PULL_REQUEST_NUMBER
          }

          dotnet pack SmartFormat --verbosity minimal --configuration release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=../../artifacts /p:ContinuousIntegrationBuild=true /p:Version=$version /p:FileVersion=$versionFile
    test_script:
      - cmd: nuget install Appveyor.TestLogger
      - cmd: dotnet test --no-build --framework net5.0 --test-adapter-path:. --logger:Appveyor SmartFormat.sln /p:configuration=release /p:AltCover=true /p:AltCoverXmlReport="coverage.xml" /p:AltCover=true /p:AltCoverStrongNameKey="..\SmartFormat\SmartFormat.snk" /p:AltCoverAssemblyExcludeFilter="SmartFormat.Tests|NUnit3.TestAdapter" /p:AltCoverLineCover="true"
      - cmd: nuget install codecov -excludeversion
      - cmd: .\Codecov\Tools\win7-x86\codecov.exe -f ".\SmartFormat.Tests\coverage.net5.0.xml" -n net5.0win
    artifacts:
      - path: 'artifacts\*.nupkg'
      - path: 'artifacts\*.snupkg'
    deploy:
      - provider: NuGet
        api_key:
          secure: OxZeF53X5DcHmg+t3zMNZP9NhlpSJHEQN6O4zuz6/FT3SCaBh8kp+tbftzt+nlhi
        on:
          branch: main
  -
    matrix:
      only:
        - job_name: linux
    build_script:
      - mkdir $APPVEYOR_BUILD_FOLDER/Src
      - cd $APPVEYOR_BUILD_FOLDER/Src
      - dotnet --version
      - dotnet restore --verbosity quiet
      - dotnet add ./SmartFormat.Tests/SmartFormat.Tests.csproj package AltCover
      - dotnet build SmartFormat.sln /verbosity:minimal /t:rebuild /p:configuration=release /nowarn:CS1591,CS0618 
    test_script:
      - nuget install Appveyor.TestLogger
      - dotnet test --no-build --framework net5.0 --test-adapter-path:. --logger:Appveyor SmartFormat.sln /p:configuration=release /p:AltCover=true /p:AltCoverXmlReport="coverage.xml" /p:AltCover=true /p:AltCoverStrongNameKey="..\SmartFormat\SmartFormat.snk" /p:AltCoverAssemblyExcludeFilter="SmartFormat.Tests|NUnit3.TestAdapter" /p:AltCoverLineCover="true"
      - bash <(curl -s https://codecov.io/bash) -f ./SmartFormat.Tests/coverage.net5.0.xml -n net5.0linux
